name: test
on:
  push:
    branches:
      - main
    tags:
      - '*'
  release:
    types:
      - created
  workflow_dispatch:
    inputs:
      b:
        type: boolean
        description: "run b"
        default: true
      c:
        type: boolean
        description: "run c"
        default: false
      d:
        type: boolean
        description: "run d"
        default: false
jobs:
  #######################################################################
  a:
    name: a
    runs-on: ubuntu-latest
    steps:
      - run: echo "A"
      - id: set
        run: |
          echo "::set-output name=run_job_b::yes"
    outputs:
      run_job_b: ${{ steps.set.outputs.run_job_b }}
  #######################################################################
  b:
    name: b
    runs-on: ubuntu-latest
    needs:
      - a
    if: ${{ always() && ((github.event_name == 'workflow_dispatch' && github.event.inputs.b == 'true') || ((github.event_name == 'push') && (needs.a.result == 'success' || needs.a.result == 'skipped'))) }}
    steps:
      - run: echo "B"
  #######################################################################
  c:
    name: c
    runs-on: ubuntu-latest
    needs:
      - a
      - b
    if: ${{ always() && ((github.event_name == 'workflow_dispatch' && github.event.inputs.c == 'true') || ((github.event_name == 'push' && contains(github.ref, 'refs/tags/')) && (needs.b.result == 'success' || needs.b.result == 'skipped'))) }}
    steps:
      - run: echo "C"
  #######################################################################
  d:
    name: c
    runs-on: ubuntu-latest
    needs:
      - a
      - b
    if: ${{ always() && ((github.event_name == 'workflow_dispatch' && github.event.inputs.d == 'true') || ((github.event_name == 'release' && github.event.action == 'created') && (needs.c.result == 'success' || needs.c.result == 'skipped'))) }}
    steps:
      - run: echo "D"
